"""risk rules issues and rectifications

Revision ID: 40269a507d29
Revises: b08ca665dc62
Create Date: 2026-08-24 13:44:34.143231
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40269a507d29'
down_revision: str | None = 'b08ca665dc62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issues',
    sa.Column('issue_no', sa.String(length=64), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('audio_file_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('risk', sa.String(length=16), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('legacy_state', sa.String(length=64), nullable=True),
    sa.Column('review_status', sa.String(length=32), nullable=False),
    sa.Column('employee_view_status', sa.String(length=32), nullable=False),
    sa.Column('appeal_status', sa.String(length=32), nullable=False),
    sa.Column('remediation_status', sa.String(length=32), nullable=False),
    sa.Column('close_status', sa.String(length=32), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.String(length=512), nullable=True),
    sa.Column('dismissed_reason', sa.String(length=512), nullable=True),
    sa.Column('rectify_task_id', sa.Uuid(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submit_comment', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appeal_reason', sa.Text(), nullable=True),
    sa.Column('appeal_reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('appeal_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('appeal_review_comment', sa.String(length=512), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rectify_task_id'], ['rectifications.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_issue_tenant_occurred', 'issues', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_issue_tenant_review', 'issues', ['tenant_id', 'review_status'], unique=False)
    op.create_index('ix_issue_tenant_store', 'issues', ['tenant_id', 'store_id'], unique=False)
    op.create_index(op.f('ix_issues_audio_file_id'), 'issues', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_issues_conversation_id'), 'issues', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_issues_employee_id'), 'issues', ['employee_id'], unique=False)
    op.create_index(op.f('ix_issues_store_id'), 'issues', ['store_id'], unique=False)
    op.create_index(op.f('ix_issues_tenant_id'), 'issues', ['tenant_id'], unique=False)
    op.create_table('rectifications',
    sa.Column('issue_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('submit_comment', sa.Text(), nullable=True),
    sa.Column('confirmed_by', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rectifications_employee_id'), 'rectifications', ['employee_id'], unique=False)
    op.create_index(op.f('ix_rectifications_issue_id'), 'rectifications', ['issue_id'], unique=False)
    op.create_index(op.f('ix_rectifications_store_id'), 'rectifications', ['store_id'], unique=False)
    op.create_index(op.f('ix_rectifications_tenant_id'), 'rectifications', ['tenant_id'], unique=False)
    op.create_table('risk_rules',
    sa.Column('rule_set', sa.String(length=32), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('keywords', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_risk_rule_tenant_code')
    )
    op.create_index(op.f('ix_risk_rules_tenant_id'), 'risk_rules', ['tenant_id'], unique=False)
    op.create_table('risk_rule_versions',
    sa.Column('rule_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('changed_by', sa.Uuid(), nullable=True),
    sa.Column('change_note', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['risk_rules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'rule_id', 'version_no', name='uq_rule_version_tenant')
    )
    op.create_index(op.f('ix_risk_rule_versions_rule_id'), 'risk_rule_versions', ['rule_id'], unique=False)
    op.create_index(op.f('ix_risk_rule_versions_tenant_id'), 'risk_rule_versions', ['tenant_id'], unique=False)
    op.create_table('risk_segments',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('audio_file_id', sa.Uuid(), nullable=True),
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('issue_id', sa.Uuid(), nullable=True),
    sa.Column('rule_code', sa.String(length=64), nullable=False),
    sa.Column('rule_name', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('matched_text', sa.Text(), nullable=False),
    sa.Column('matched_keywords', sa.JSON(), nullable=False),
    sa.Column('speaker', sa.String(length=64), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['risk_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_seg_conv', 'risk_segments', ['tenant_id', 'conversation_id'], unique=False)
    op.create_index(op.f('ix_risk_segments_conversation_id'), 'risk_segments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_risk_segments_tenant_id'), 'risk_segments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_segments_tenant_id'), table_name='risk_segments')
    op.drop_index(op.f('ix_risk_segments_conversation_id'), table_name='risk_segments')
    op.drop_index('ix_risk_seg_conv', table_name='risk_segments')
    op.drop_table('risk_segments')
    op.drop_index(op.f('ix_risk_rule_versions_tenant_id'), table_name='risk_rule_versions')
    op.drop_index(op.f('ix_risk_rule_versions_rule_id'), table_name='risk_rule_versions')
    op.drop_table('risk_rule_versions')
    op.drop_index(op.f('ix_risk_rules_tenant_id'), table_name='risk_rules')
    op.drop_table('risk_rules')
    op.drop_index(op.f('ix_rectifications_tenant_id'), table_name='rectifications')
    op.drop_index(op.f('ix_rectifications_store_id'), table_name='rectifications')
    op.drop_index(op.f('ix_rectifications_issue_id'), table_name='rectifications')
    op.drop_index(op.f('ix_rectifications_employee_id'), table_name='rectifications')
    op.drop_table('rectifications')
    op.drop_index(op.f('ix_issues_tenant_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_store_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_employee_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_conversation_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_audio_file_id'), table_name='issues')
    op.drop_index('ix_issue_tenant_store', table_name='issues')
    op.drop_index('ix_issue_tenant_review', table_name='issues')
    op.drop_index('ix_issue_tenant_occurred', table_name='issues')
    op.drop_table('issues')
    # ### end Alembic commands ###
