"""org device and imports

Revision ID: 47b90b3c601f
Revises: c42d003559fc
Create Date: 2026-08-24 12:12:45.836864
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b90b3c601f'
down_revision: str | None = 'c42d003559fc'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # PG 部分唯一索引: 同一租户同一设备同一时刻仅一个 ACTIVE 绑定 (SQLite 由应用层校验)
    # 必须在 device_bindings 建表后执行, 故放在 upgrade 末尾 (见文件尾部)。
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('device_code', sa.String(length=64), nullable=False),
    sa.Column('device_type', sa.String(length=32), nullable=False),
    sa.Column('vendor', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('online_status', sa.String(length=32), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('battery_level', sa.Integer(), nullable=True),
    sa.Column('firmware_version', sa.String(length=64), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'device_code', name='uq_device_tenant_code')
    )
    op.create_index(op.f('ix_devices_tenant_id'), 'devices', ['tenant_id'], unique=False)
    op.create_table('import_batches',
    sa.Column('import_type', sa.String(length=32), nullable=False),
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('success_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('error_summary', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_batches_tenant_id'), 'import_batches', ['tenant_id'], unique=False)
    op.create_table('organization_nodes',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['organization_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_org_node_tenant_code')
    )
    op.create_index(op.f('ix_organization_nodes_tenant_id'), 'organization_nodes', ['tenant_id'], unique=False)
    op.create_table('positions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_position_tenant_code')
    )
    op.create_index(op.f('ix_positions_tenant_id'), 'positions', ['tenant_id'], unique=False)
    op.create_table('import_items',
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('row_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.String(length=1024), nullable=True),
    sa.Column('legacy_key', sa.String(length=128), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['import_batches.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_items_batch_id'), 'import_items', ['batch_id'], unique=False)
    op.create_index(op.f('ix_import_items_tenant_id'), 'import_items', ['tenant_id'], unique=False)
    op.create_table('stores',
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['organization_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_store_tenant_code')
    )
    op.create_index(op.f('ix_stores_node_id'), 'stores', ['node_id'], unique=False)
    op.create_index(op.f('ix_stores_tenant_id'), 'stores', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('employee_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('mobile', sa.String(length=32), nullable=False),
    sa.Column('job_title', sa.String(length=128), nullable=True),
    sa.Column('organization_node_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('manager_id', sa.Uuid(), nullable=True),
    sa.Column('employment_status', sa.String(length=32), nullable=False),
    sa.Column('account_status', sa.String(length=32), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.Column('left_at', sa.Date(), nullable=True),
    sa.Column('extra_meta', sa.JSON(), nullable=True),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['manager_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_node_id'], ['organization_nodes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'employee_no', name='uq_employee_tenant_no'),
    sa.UniqueConstraint('tenant_id', 'mobile', name='uq_employee_tenant_mobile')
    )
    op.create_index(op.f('ix_employees_organization_node_id'), 'employees', ['organization_node_id'], unique=False)
    op.create_index(op.f('ix_employees_store_id'), 'employees', ['store_id'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('device_binding_requests',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_binding_requests_device_id'), 'device_binding_requests', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_binding_requests_employee_id'), 'device_binding_requests', ['employee_id'], unique=False)
    op.create_index(op.f('ix_device_binding_requests_tenant_id'), 'device_binding_requests', ['tenant_id'], unique=False)
    op.create_table('device_bindings',
    sa.Column('device_id', sa.Uuid(), nullable=False),
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('binding_status', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_binding_tenant_device', 'device_bindings', ['tenant_id', 'device_id'], unique=False)
    op.create_index(op.f('ix_device_bindings_device_id'), 'device_bindings', ['device_id'], unique=False)
    op.create_index(op.f('ix_device_bindings_employee_id'), 'device_bindings', ['employee_id'], unique=False)
    op.create_index(op.f('ix_device_bindings_tenant_id'), 'device_bindings', ['tenant_id'], unique=False)
    op.create_table('recording_consents',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('policy_name', sa.String(length=128), nullable=False),
    sa.Column('policy_version', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('device_info', sa.String(length=256), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'policy_version', name='uq_consent_employee_version')
    )
    op.create_index(op.f('ix_recording_consents_employee_id'), 'recording_consents', ['employee_id'], unique=False)
    op.create_index(op.f('ix_recording_consents_tenant_id'), 'recording_consents', ['tenant_id'], unique=False)
    # ### end Alembic commands ###

    # PG 部分唯一索引: 同一租户同一设备同一时刻仅一个 ACTIVE 绑定
    # (SQLite 测试环境由应用层 DeviceService 校验)
    op.execute(
        """CREATE UNIQUE INDEX IF NOT EXISTS uq_device_active_binding
        ON device_bindings (tenant_id, device_id)
        WHERE binding_status = 'ACTIVE'"""
    )

    # 迁移工具元数据: 批次 + 明细 (PocketBase → PostgreSQL)
    op.create_table(
        'migration_batches',
        sa.Column('id', sa.String(length=32), nullable=False),
        sa.Column('tenant_id', sa.Uuid(), nullable=False),
        sa.Column('status', sa.String(length=16), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_migration_batches_tenant_id'), 'migration_batches', ['tenant_id'], unique=False)
    op.create_table(
        'migration_items',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('batch_id', sa.String(length=32), nullable=False),
        sa.Column('target_table', sa.String(length=64), nullable=False),
        sa.Column('target_id', sa.String(length=36), nullable=False),
        sa.Column('source_collection', sa.String(length=64), nullable=False),
        sa.Column('source_id', sa.String(length=64), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
        sa.ForeignKeyConstraint(['batch_id'], ['migration_batches.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_index(op.f('ix_migration_items_batch_id'), 'migration_items', ['batch_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_migration_items_batch_id'), table_name='migration_items')
    op.drop_table('migration_items')
    op.drop_index(op.f('ix_migration_batches_tenant_id'), table_name='migration_batches')
    op.drop_table('migration_batches')
    op.execute("DROP INDEX IF EXISTS uq_device_active_binding")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recording_consents_tenant_id'), table_name='recording_consents')
    op.drop_index(op.f('ix_recording_consents_employee_id'), table_name='recording_consents')
    op.drop_table('recording_consents')
    op.drop_index(op.f('ix_device_bindings_tenant_id'), table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_employee_id'), table_name='device_bindings')
    op.drop_index(op.f('ix_device_bindings_device_id'), table_name='device_bindings')
    op.drop_index('ix_binding_tenant_device', table_name='device_bindings')
    op.drop_table('device_bindings')
    op.drop_index(op.f('ix_device_binding_requests_tenant_id'), table_name='device_binding_requests')
    op.drop_index(op.f('ix_device_binding_requests_employee_id'), table_name='device_binding_requests')
    op.drop_index(op.f('ix_device_binding_requests_device_id'), table_name='device_binding_requests')
    op.drop_table('device_binding_requests')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_store_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_organization_node_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_stores_tenant_id'), table_name='stores')
    op.drop_index(op.f('ix_stores_node_id'), table_name='stores')
    op.drop_table('stores')
    op.drop_index(op.f('ix_import_items_tenant_id'), table_name='import_items')
    op.drop_index(op.f('ix_import_items_batch_id'), table_name='import_items')
    op.drop_table('import_items')
    op.drop_index(op.f('ix_positions_tenant_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_organization_nodes_tenant_id'), table_name='organization_nodes')
    op.drop_table('organization_nodes')
    op.drop_index(op.f('ix_import_batches_tenant_id'), table_name='import_batches')
    op.drop_table('import_batches')
    op.drop_index(op.f('ix_devices_tenant_id'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
