"""recording ingestion and transcription

Revision ID: b08ca665dc62
Revises: 47b90b3c601f
Create Date: 2026-08-24 13:30:31.351274
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b08ca665dc62'
down_revision: str | None = '47b90b3c601f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_files',
    sa.Column('file_name', sa.String(length=256), nullable=False),
    sa.Column('object_key', sa.String(length=512), nullable=False),
    sa.Column('storage_provider', sa.String(length=32), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=16), nullable=False),
    sa.Column('device_code', sa.String(length=64), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('hotwords', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('qc_result', sa.String(length=32), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=True),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_files_employee_id'), 'audio_files', ['employee_id'], unique=False)
    op.create_index(op.f('ix_audio_files_store_id'), 'audio_files', ['store_id'], unique=False)
    op.create_index(op.f('ix_audio_files_tenant_id'), 'audio_files', ['tenant_id'], unique=False)
    op.create_index('ix_audio_tenant_occurred', 'audio_files', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index('ix_audio_tenant_status', 'audio_files', ['tenant_id', 'status'], unique=False)
    op.create_table('conversations',
    sa.Column('audio_file_id', sa.Uuid(), nullable=False),
    sa.Column('store_id', sa.Uuid(), nullable=True),
    sa.Column('employee_id', sa.Uuid(), nullable=True),
    sa.Column('device_code', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('qc_result', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('speaker_aliases', sa.JSON(), nullable=True),
    sa.Column('marks_json', sa.JSON(), nullable=True),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('legacy_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('audio_file_id')
    )
    op.create_index('ix_conv_tenant_occurred', 'conversations', ['tenant_id', 'started_at'], unique=False)
    op.create_index(op.f('ix_conversations_employee_id'), 'conversations', ['employee_id'], unique=False)
    op.create_index(op.f('ix_conversations_store_id'), 'conversations', ['store_id'], unique=False)
    op.create_index(op.f('ix_conversations_tenant_id'), 'conversations', ['tenant_id'], unique=False)
    op.create_table('processing_jobs',
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('audio_file_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('remote_job_id', sa.String(length=128), nullable=True),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_polled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['audio_file_id'], ['audio_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_tenant_status', 'processing_jobs', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_processing_jobs_audio_file_id'), 'processing_jobs', ['audio_file_id'], unique=False)
    op.create_index(op.f('ix_processing_jobs_tenant_id'), 'processing_jobs', ['tenant_id'], unique=False)
    op.create_table('text_versions',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('full_text', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('segments_json', sa.JSON(), nullable=True),
    sa.Column('marks_json', sa.JSON(), nullable=True),
    sa.Column('speaker_aliases', sa.JSON(), nullable=True),
    sa.Column('edited_by', sa.Uuid(), nullable=True),
    sa.Column('edit_reason', sa.String(length=256), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'conversation_id', 'version_no', name='uq_text_version_conv_no')
    )
    op.create_index(op.f('ix_text_versions_conversation_id'), 'text_versions', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_text_versions_tenant_id'), 'text_versions', ['tenant_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('segment_no', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=64), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seg_conv_version', 'transcript_segments', ['tenant_id', 'conversation_id', 'version_no', 'segment_no'], unique=False)
    op.create_index(op.f('ix_transcript_segments_conversation_id'), 'transcript_segments', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_transcript_segments_tenant_id'), 'transcript_segments', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_segments_tenant_id'), table_name='transcript_segments')
    op.drop_index(op.f('ix_transcript_segments_conversation_id'), table_name='transcript_segments')
    op.drop_index('ix_seg_conv_version', table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_text_versions_tenant_id'), table_name='text_versions')
    op.drop_index(op.f('ix_text_versions_conversation_id'), table_name='text_versions')
    op.drop_table('text_versions')
    op.drop_index(op.f('ix_processing_jobs_tenant_id'), table_name='processing_jobs')
    op.drop_index(op.f('ix_processing_jobs_audio_file_id'), table_name='processing_jobs')
    op.drop_index('ix_job_tenant_status', table_name='processing_jobs')
    op.drop_table('processing_jobs')
    op.drop_index(op.f('ix_conversations_tenant_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_store_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_employee_id'), table_name='conversations')
    op.drop_index('ix_conv_tenant_occurred', table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_audio_tenant_status', table_name='audio_files')
    op.drop_index('ix_audio_tenant_occurred', table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_tenant_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_store_id'), table_name='audio_files')
    op.drop_index(op.f('ix_audio_files_employee_id'), table_name='audio_files')
    op.drop_table('audio_files')
    # ### end Alembic commands ###
